use Mix.Config

# NOTE: this file contains some security keys/certs that are *not* secrets, and are only used for local development purposes.

host = "hubs.local"
host_front = "host.docker.internal"
cors_proxy_host = "hubs-proxy.local"
assets_host = "hubs-assets.local"
link_host = "hubs-link.local"

# To run reticulum across a LAN for local testing, uncomment and change the line below to the LAN IP
# host = cors_proxy_host = "192.168.1.27"

dev_janus_host = "hubs.local"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :ret, RetWeb.Endpoint,
  url: [scheme: "https", host: host, port: 4000],
  static_url: [scheme: "https", host: host, port: 4000],
  https: [
    port: 4000,
    otp_app: :ret,
    cipher_suite: :strong,
    keyfile: "#{File.cwd!()}/priv/cert/key.pem",
    certfile: "#{File.cwd!()}/priv/cert/cert.pem"
  ],
  cors_proxy_url: [scheme: "https", host: cors_proxy_host, port: 4000],
  assets_url: [scheme: "https", host: assets_host, port: 4000],
  link_url: [scheme: "https", host: link_host, port: 4000],
  imgproxy_url: [scheme: "http", host: host, port: 5000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  # This config value is for local development only.
  secret_key_base: "txlMOtlaY5x3crvOCko4uV5PM29ul3zGo1oBGNO3cDXx+7GHLKqt0gR9qzgThxb5",
  allowed_origins: "*",
  allow_crawlers: true

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem

# The `http:` config above can be replaced with:

#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ret, RetWeb.Endpoint,
  # static_url: [scheme: "https", host: "assets-prod.reticulum.io", port: 443],
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/ret_web/views/.*(ex)$},
      ~r{lib/ret_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

env_db_host = "#{System.get_env("DB_HOST")}"

# Configure your database
config :ret, Ret.Repo,
  username: "postgres",
  password: "postgres",
  database: "ret_dev",
  hostname: if(env_db_host == "", do: "localhost", else: env_db_host),
  template: "template0",
  pool_size: 10

config :ret, Ret.SessionLockRepo,
  username: "postgres",
  password: "postgres",
  database: "ret_dev",
  hostname: if(env_db_host == "", do: "localhost", else: env_db_host),
  template: "template0",
  pool_size: 10

config :ret, RetWeb.Plugs.HeaderAuthorization,
  header_name: "x-ret-admin-access-key",
  header_value: "admin-only"

config :ret, Ret.SlackClient,
  client_id: "",
  client_secret: "",
  bot_token: ""

# Token is our randomly generated auth token to append to Slacks slash command
# As a query param "token"
config :ret, RetWeb.Api.V1.SlackController, token: ""

config :ret, Ret.DiscordClient,
  client_id: "",
  client_secret: "",
  bot_token: ""

config :ret, RetWeb.Api.V1.WhatsNewController, token: ""

config :ret, RetWeb.Plugs.DashboardHeaderAuthorization, dashboard_access_key: ""

# Allow any origin for API access in dev
config :cors_plug, origin: ["*"]

config :ret,
  # This config value is for local development only.
  upload_encryption_key: "a8dedeb57adafa7821027d546f016efef5a501bd",
  bot_access_key: ""

config :ret, Ret.PageOriginWarmer,
  hubs_page_origin: "https://#{host_front}:8080",
  admin_page_origin: "https://#{host_front}:8989",
  spoke_page_origin: "https://#{host_front}:9090",
  insecure_ssl: true

config :ret, Ret.HttpUtils, insecure_ssl: true

config :ret, Ret.MediaResolver,
  giphy_api_key: nil,
  deviantart_client_id: nil,
  deviantart_client_secret: nil,
  imgur_mashape_api_key: nil,
  imgur_client_id: nil,
  youtube_api_key: nil,
  sketchfab_api_key: nil,
  ytdl_host: nil,
  photomnemonic_endpoint: "https://uvnsm9nzhe.execute-api.us-west-1.amazonaws.com/public"

config :ret, Ret.Speelycaptor, speelycaptor_endpoint: "https://1dhaogh2hd.execute-api.us-west-1.amazonaws.com/public"

config :ret, Ret.Storage,
  host: "https://#{host}:4000",
  storage_path: "storage/dev",
  ttl: 60 * 60 * 24

asset_hosts =
  "https://localhost:4000 https://localhost:8080 " <>
    "https://#{host}:4000 https://#{host}:8080 https://#{host}:3000 https://#{host}:8989 https://#{host}:9090 https://#{
      cors_proxy_host
    }:4000 " <>
    "https://assets-prod.reticulum.io https://asset-bundles-dev.reticulum.io https://asset-bundles-prod.reticulum.io"

websocket_hosts =
  "https://localhost:4000 https://localhost:8080 wss://localhost:4000 " <>
    "https://#{host}:4000 https://#{host}:8080 wss://#{host}:4000 wss://#{host}:8080 wss://#{host}:8989 wss://#{host}:9090 " <>
    "wss://#{host}:4000 wss://#{host}:8080 https://#{host}:8080 https://hubs.local:8080 wss://hubs.local:8080 https://hubs.local:9090"

config :ret, RetWeb.Plugs.AddCSP,
  script_src: asset_hosts,
  font_src: asset_hosts,
  style_src: asset_hosts,
  connect_src:
    "https://#{host}:8080 https://#{host}:8080 https://sentry.prod.mozaws.net #{asset_hosts} #{websocket_hosts} https://www.mozilla.org",
  img_src: asset_hosts,
  media_src: asset_hosts,
  manifest_src: asset_hosts

config :ret, Ret.Mailer, adapter: Bamboo.LocalAdapter

config :ret, RetWeb.Email, from: "info@hubs-mail.com"

# add yryuu
config :ret, Ret.PermsToken, perms_key: "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAsKd4W+n80K67Pzjd2/46oa9GnQbRc2eofcghzjTRLZYOXIXR\njEF026y5P3f5SvQsozXT4Ewksqjdafl3MenC7PPWawfLvfH7dr+XkJdIEQNnLtmm\n881t9x9MueY/Ctv4kIyy/ooaoZDV5j2hj/SZjyD5p2CJVYWoP1tRPsnIfy/ISoqH\n4ssqsg7fMX6vs8slpHOHua0sM/rna+RxGfX/mcKkNhSdSPeWuldVF9omxIbvXPTH\nTiNC4gRvIandcZpzOCEs7agsPbjwsYUyEbo24bMpWxE3f4k7/CGa/PiImO14HkZu\nTK9criqCEjV8q6Yv0y+SHfpr1gv5KsYLkF6ViwIDAQABAoIBAD7grS+SHqGswAtl\n01o9qGLqf2jfB2hbahazSI0cMaRXN+9o1khk+BJE7X8Q1hP+y3CgdTTuBVXuUzko\nSWvjt7UdqaFZGgUW/5mp4mnd3xHnMy/y2sEGyvBeHLJCqQfVeikBW6jMQWRmqCwW\nnc4ekxXl99bCvr9JHrTGbSm7KvlR0b21AJgsNN0Uc7qTAQwhasjW5YHpQRLxZuiZ\nGeTzFIJx3qfxlXWdDEE5qtlFkxRa+Mi/44aKa2CUMJ0/DbqB7k4i4eZ/Av5AaKn9\n0pRFhna7E6J+BaoF/obMRcAFkbtxoVIcgIp5CKJyzh2eSuHxsJssag5uLsOrj0Ca\nCOra2PkCgYEA502GmyCetAXDjcB1ugySl7iUk44Z6YeCnB03H5JgHawyoQAb2cBc\nup+PHchHdeixEdWnF8fhqcqPCoK4xyyNkZ6yOvM6bBEk35xbi3QfWiaqLEmbEWbj\nBz/8+DQBXjG8mG36EEDYm0igxl25J/3+wzyX05APeZYohZhPRO0Esk0CgYEAw4Qr\nAFtbTUvenmTP/A+Pe8zAQSs0aKdqnFeknED59s53x6pt9H/PEQUsoY4DQzE3Oo/H\nf6CeDB1KbRacPn7pP9jJXOtwSpdo6pGvF+dGZSaRQPXrZc1eWbtgigYGCeWRdk3k\nitVEkG88DNhbRTZ6BFrWPbduauSRH08RJbBK4zcCgYAP4rYs70eXC5JLqP0s4vIq\nc2XY4HiNHl5tBGClzXLGdu4fOpevE9QKiSzWGcw2n92RYQAR1Qt9ksjSKvovy7KJ\nXsHU5KGNjHvg06dB457HnUIwunlo740GEXH5RfEWHApc2ajD9wApYgqQtR0jTwFx\nPTccM5esfRCZZEWFcVXSPQKBgQCFNcvGlngCliq7aJx8dG2iP8LNpA41L7vngZ9a\nBrtIeSwLEgeQinQeeJQMDqISabnjYIrgXiLQxjQrVzhlLDrnkWDAunjrmXWWPGQ7\nuQuxZzGYPPWBiwc5w/zmjWwX2h3dqPyJyvzIG8GiTtcAtTk1Nl659fx5P/nQhyJ7\ntz2OyQKBgAa/nq27NP5eJ1XAJBgimrBzxBXEPZkepiAzearp8HOAkkzFSFJJhlGX\nfJn17sAheVEAmfnzQhzxBwY04haZ9QsaweLiLYNDMng9fyIyj/ivbPeJ/yuhzPWB\nMcyI9hgTdULDK3RUUGLcu5oR5ynuvdBEwq9aqJfzHM4lRsKO9yuN\n-----END RSA PRIVATE KEY-----"
config :ret, Ret.OAuthToken, oauth_token_key: ""

config :ret, Ret.Guardian,
  issuer: "ret",
  # This config value is for local development only.
  secret_key: "47iqPEdWcfE7xRnyaxKDLt9OGEtkQG3SycHBEMOuT2qARmoESnhc76IgCUjaQIwX",
  ttl: {12, :weeks}

config :web_push_encryption, :vapid_details,
  subject: "mailto:admin@mozilla.com",
  public_key: "BAb03820kHYuqIvtP6QuCKZRshvv_zp5eDtqkuwCUAxASBZMQbFZXzv8kjYOuLGF16A3k8qYnIN10_4asB-Aw7w",
  # This config value is for local development only.
  private_key: "w76tXh1d3RBdVQ5eINevXRwW6Ow6uRcBa8tBDOXfmxM"

config :sentry,
  environment_name: :dev,
  json_library: Poison,
  included_environments: [],
  tags: %{
    env: "dev"
  }

config :ret, Ret.Habitat, ip: "127.0.0.1", http_port: 9631

config :ret, Ret.JanusLoadStatus, default_janus_host: dev_janus_host, janus_port: 4443
config :ret, Ret.RoomAssigner, balancer_weights: [{600, 1}, {300, 50}, {0, 500}]

config :ret, RetWeb.PageController,
  skip_cache: true,
  assets_path: "storage/assets",
  docs_path: "storage/docs"

config :ret, Ret.HttpUtils, insecure_ssl: true

config :ret, Ret.Meta, phx_host: host

config :ret, Ret.Locking,
  lock_timeout_ms: 1000 * 60 * 15,
  session_lock_db: [
    username: "postgres",
    password: "postgres",
    database: "ret_dev",
    hostname: if(env_db_host == "", do: "localhost", else: env_db_host)
  ]

config :ret, Ret.Repo.Migrations.AdminSchemaInit, postgrest_password: "password"
config :ret, Ret.StatsJob, node_stats_enabled: false, node_gauges_enabled: false
config :ret, Ret.Coturn, realm: "ret"
